### ISSUE TITLE
Abiility to set headers

### ISSUE THREAD

**Issue by crowlKats** [ricea/websocketstream-explainer#11] opened 2021-02-02 15:53 UTC
For example, with `fetch`, one can specify headers. Sadly normal WS APi doesnt allow this. It would be great if one could set additional headers, or maybe at least cookie headers.

**Comment by yutakahirano** [comment] 2021-02-04 05:08
This is a dupe of https://github.com/whatwg/html/issues/3062.

**Closed by yutakahirano** 2021-02-04 05:08 UTC
